### PR TITLE
26 - Authentication, User Profile, and Tasks

### PR DESCRIPTION
**Pull request by pgeorge2**
- Added djangorestframework-simplejwt package in base.in to support JWT Token authentication.
- Made UserViewSet to editable by authenticted users.
- Added Repository Model with its App config the urls in repository folder.
- Added Authenctication class in rest framework for JWT support
- Added github login env variables in compose file.
- Added job_title required field in TeamMember model
- Included all allauth urls which handles github login at the moment.
- Added routes for team_members api
- Made the repository field type to ForeignKey in UserEarnings model.
- Modified the filterset_fields to repository__display_name.

### CODE REVIEW

**Comment by buckyroberts** [comment]
Frontend for this: https://github.com/thenewboston-developers/Website/pull/1097

**Review by vosi — CHANGES_REQUESTED** [review]
@pgeorge2 please, fix pipeline errors

also, you haven't provided a single test

**Comment by pgeorge2** [comment]
@vosi Sure. Fixing the pipeline error and Adding tests for the implemented features.

**Comment by pgeorge2** [comment]
Hi @vosi initially, I was getting the pipeline error due to flak8 liniting and after fixing it, I got pytest error because we changed some of the fields in UserEraning model and TeamMembers model. I tried to fixed those tests and run the pytest in local system and I am able to pass 43 tests out of 46 and 3 are failing. Out of these 3, when I run 2 tests individually, it is running fine but those are not working when running all tests together for some strange reason.

I attached the test summay for reference. Can you please help me out to solve the mentioned issue?

image

**Comment by vosi** [comment]
@pgeorge2 according to the log, you have to fix the test. ... the fix is pretty obvious ... I don't even know how to explain the problem ... other that test log

**Comment by buckyroberts** [comment]
Closes #26

**Pull request merged**
