### PR TITLE
Feat/caching

### PR DESCRIPTION
**Pull request by ThaDeveloper**
Closes https://github.com/thenewboston-developers/Website-API/issues/124

### CODE REVIEW

**Comment by ThaDeveloper** [comment]
@truyenhv We will need a `REDIS_HOST` referenced [here ](https://github.com/thenewboston-developers/Website-API/blob/07c2cbbd0f8f34d1b9be3a053906e402abfbfc82/config/settings/base.py#L83)

**Comment by truyenhv** [comment]
We need for dev right?

**Comment by ThaDeveloper** [comment]
Both dev and prod

**Comment by ThaDeveloper** [comment]
@truyenhv Did you work on the Redis setup?

**Comment by truyenhv** [comment]
ah yes. we already had redis cluster.

**Comment by ThaDeveloper** [comment]
You could review the pr

**Review by truyenhv — APPROVED** [review]

**Comment by truyenhv** [comment]
I think we could test on dev now

**Pull request merged**
