### PR TITLE
Projects mile stones list, update CI/CD with ECS

### PR DESCRIPTION
**Pull request by ThaDeveloper**

### CODE REVIEW

**Review by truyenhv — APPROVED** [review]

**Comment by ThaDeveloper** [comment]
dev to prod

**Review by truyenhv — APPROVED** [review]

**Comment by ThaDeveloper** [comment]
@truyenhv is this not ready for prod?

**Comment by truyenhv** [comment]
hmm. not yet. Let me update for production. Just think that we need to test more on development environment

**Comment by ThaDeveloper** [comment]
Reason I'm  asking is because  the frontend could  be waiting  on the milestones feature

**Comment by truyenhv** [comment]
if we merge this request. It still deploy to production. No worries

**Pull request merged**
