### PR TITLE
Feat: Projects

### PR DESCRIPTION
**Pull request by ThaDeveloper**
Closes https://github.com/thenewboston-developers/Website-API/issues/78

### CODE REVIEW

**Comment by ma2b0043** [comment]
@ThaDeveloper will the projects be arranged in alphabetical order(on the project page)?

**Comment by ThaDeveloper** [comment]
@ma2b0043 Currently  by both creation date and alphabetical

**Comment by ma2b0043** [comment]
> @ma2b0043 Currently by both creation date and alphabetical

While finalizing the design page of projects, we decided that we should sort them alphabetically(only) because if we use 2 metric for rearranging them, it wouldn't look good(I'm sure you would agree).

**Comment by ThaDeveloper** [comment]
It's  just a UX preference, will update

**Comment by ma2b0043** [comment]
> It's just a UX preference, will update

Thank you, actually the design team, updated the designs for this project page(just now) as well, so kindly see that as well.

**Review by ma2b0043 — APPROVED** [review]

**Comment by ThaDeveloper** [comment]
Updated. ready to merge

**Pull request merged**
