### PR TITLE
Team Page API Updates #27

### PR DESCRIPTION
**Pull request by dhakal0kushal**

### CODE REVIEW

**Comment by dhakal0kushal** [comment]
oh okay
I'll need to study the pytest now :P

**Comment by ThaDeveloper** [comment]
@dhakal0kushal what's the update on this PR

**Comment by dhakal0kushal** [comment]
give me one more day for this
I'm learning pytest hoping to complete it assap

**Comment by dhakal0kushal** [comment]
Hi @ThaDeveloper  you can take this PR from here
i don't really know the logic to write tests so I'll learn it from yours ^_^

**Comment by ThaDeveloper** [comment]
> Hi @ThaDeveloper you can take this PR from here
> i don't really know the logic to write tests so I'll learn it from yours ^_^

@dhakal0kushal No problem

**Pull request closed without merging**
